pulsar:
  enabled: true
  URL: "pulsar://pulsar:6650"
  jobsetEventsTopic: "jobset-events"
  redisFromPulsarSubscription: "RedisFromPulsar"
  pulsarFromPulsarSubscription: "PulsarFromPulsar"
  hostnameSuffix: "svc"
  certNameSuffix: "ingress-tls-certificate"
  # TODO:
  # compression
  # tls
  # ca, path to
  # jwt, if enabled
  # jwt, path to token file
